module.exports = {
  classMinimum: require('./class.minimum.json'),
  classMultilingual: require('./class.multilingual.json'),
  classAllFields: require('./class.all.fields.json'),
  generalizationMinimum: require('./generalization.minimum.json'),
  generalizationAllFields: require('./generalization.all.fields.json'),
  generalizationSetMinimum: require('./generalizationset.minimum.json'),
  generalizationSetAllFields: require('./generalizationset.all.fields.json'),
  literalMinimum: require('./literal.minimum.json'),
  literalAllFields: require('./literal.all.fields.json'),
  packageMinimum: require('./package.minimum.json'),
  packageAllFields: require('./package.all.fields.json'),
  propertyMinimum: require('./property.minimum.json'),
  propertyAllFields: require('./property.all.fields.json'),
  propertyMultilingual: require('./property.multilingual.json'),
  relationMinimum: require('./relation.minimum.json'),
  relationAllFields: require('./relation.all.fields.json'),
  relationMultilingual: require('./relation.multilingual.json'),
  noGeneralizationInGS: require('./no-generalizations-in-gs.json'),
  nullPropertyType: require('./null-property-type.json'),
  propertyAssignmentsAllOptions: require('./propertyassignments.all.options.json'),
  order: require('./order.json'),
};
