// @ts-check

/**
 * The documentation site has a single sidebar, autogenerated from the docs
 * folder and ordered by the `sidebar_position` frontmatter of each page.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  schema: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
